# https://github.com/line/lich/blob/master/.github/workflows/ossrh.yml

name: Deploy to OSSRH

on:
  workflow_dispatch:
    inputs:
      cond_release:
        description: 'Type "release" to release artifacts to Maven Central.'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Deploy artifacts
        env:
          ORG_GRADLE_PROJECT_repositoryUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_repositoryPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          cat libpng_version | xargs ./download_libpng_and_apply_apng_patch.sh
          ./gradlew publish

      - name: Release to Maven Central
        if: ${{ github.event.inputs.cond_release == 'release' }}
        env:
          ORG_GRADLE_PROJECT_nexusUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_nexusPassword: ${{ secrets.OSSRH_PASSWORD }}
        run: ./gradlew closeAndReleaseRepository
